
package net.assino.app1msc;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TaskManager", targetNamespace = "http://app1msc.assino.net", wsdlLocation = "wsdl/taskmanagerWSDL.xml")//file:/C:/Program%20Files/Java/jdk1.7.0_40/bin/taskmanager.1cws.xml")
public class TaskManager
    extends Service
{

    private final static URL TASKMANAGER_WSDL_LOCATION;
    private final static WebServiceException TASKMANAGER_EXCEPTION;
    private final static QName TASKMANAGER_QNAME = new QName("http://app1msc.assino.net", "TaskManager");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
        	url = ClassLoader.getSystemResource("wsdl/taskmanagerWSDL.xml");//new		
        } catch (Exception ex) {
             e = new WebServiceException(ex);
        }
        TASKMANAGER_WSDL_LOCATION = url;
        TASKMANAGER_EXCEPTION = e;
    }


    public TaskManager() {
        super(__getWsdlLocation(), TASKMANAGER_QNAME);
    }

    public TaskManager(WebServiceFeature... features) {
        super(__getWsdlLocation(), TASKMANAGER_QNAME, features);
    }

    public TaskManager(URL wsdlLocation) {
        super(wsdlLocation, TASKMANAGER_QNAME);
    }

    public TaskManager(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TASKMANAGER_QNAME, features);
    }

    public TaskManager(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TaskManager(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TaskManagerPortType
     */
    @WebEndpoint(name = "TaskManagerSoap")
    public TaskManagerPortType getTaskManagerSoap() {
        return super.getPort(new QName("http://app1msc.assino.net", "TaskManagerSoap"), TaskManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskManagerPortType
     */
    @WebEndpoint(name = "TaskManagerSoap")
    public TaskManagerPortType getTaskManagerSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://app1msc.assino.net", "TaskManagerSoap"), TaskManagerPortType.class, features);
    }

    /**
     * 
     * @return
     *     returns TaskManagerPortType
     */
    @WebEndpoint(name = "TaskManagerSoap12")
    public TaskManagerPortType getTaskManagerSoap12() {
        return super.getPort(new QName("http://app1msc.assino.net", "TaskManagerSoap12"), TaskManagerPortType.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TaskManagerPortType
     */
    @WebEndpoint(name = "TaskManagerSoap12")
    public TaskManagerPortType getTaskManagerSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://app1msc.assino.net", "TaskManagerSoap12"), TaskManagerPortType.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TASKMANAGER_EXCEPTION!= null) {
            throw TASKMANAGER_EXCEPTION;
        }
        return TASKMANAGER_WSDL_LOCATION;
    }

}
