
package net.assino.app1msc;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TaskManagerPortType", targetNamespace = "http://app1msc.assino.net")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TaskManagerPortType {


    /**
     * 
     * @param dateEnd
     * @param dateBegin
     * @param employee
     * @return
     *     returns net.assino.app1msc.TaskList
     */
    @WebMethod(operationName = "GetTasks", action = "http://app1msc.assino.net#TaskManager:GetTasks")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetTasks", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetTasks")
    @ResponseWrapper(localName = "GetTasksResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetTasksResponse")
    public TaskList getTasks(
        @WebParam(name = "DateBegin", targetNamespace = "http://app1msc.assino.net")
        XMLGregorianCalendar dateBegin,
        @WebParam(name = "DateEnd", targetNamespace = "http://app1msc.assino.net")
        XMLGregorianCalendar dateEnd,
        @WebParam(name = "Employee", targetNamespace = "http://app1msc.assino.net")
        Employee employee);

    /**
     * 
     * @return
     *     returns net.assino.app1msc.EmployeeList
     */
    @WebMethod(operationName = "GetEmployees", action = "http://app1msc.assino.net#TaskManager:GetEmployees")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetEmployees", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetEmployees")
    @ResponseWrapper(localName = "GetEmployeesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetEmployeesResponse")
    public EmployeeList getEmployees();

    /**
     * 
     * @param task
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "UpdateTask", action = "http://app1msc.assino.net#TaskManager:UpdateTask")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "UpdateTask", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.UpdateTask")
    @ResponseWrapper(localName = "UpdateTaskResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.UpdateTaskResponse")
    public boolean updateTask(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @param task
     * @return
     *     returns net.assino.app1msc.Task
     */
    @WebMethod(operationName = "CreateTask", action = "http://app1msc.assino.net#TaskManager:CreateTask")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "CreateTask", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.CreateTask")
    @ResponseWrapper(localName = "CreateTaskResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.CreateTaskResponse")
    public Task createTask(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Project
     */
    @WebMethod(operationName = "GetProjects", action = "http://app1msc.assino.net#TaskManager:GetProjects")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetProjects", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetProjects")
    @ResponseWrapper(localName = "GetProjectsResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetProjectsResponse")
    public Project getProjects();

    /**
     * 
     * @param project
     * @return
     *     returns net.assino.app1msc.ProjectStage
     */
    @WebMethod(operationName = "GetProjectsStages", action = "http://app1msc.assino.net#TaskManager:GetProjectsStages")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetProjectsStages", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetProjectsStages")
    @ResponseWrapper(localName = "GetProjectsStagesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetProjectsStagesResponse")
    public ProjectStage getProjectsStages(
        @WebParam(name = "Project", targetNamespace = "http://app1msc.assino.net")
        Project project);

    /**
     * 
     * @return
     *     returns net.assino.app1msc.StatusList
     */
    @WebMethod(operationName = "GetStatuses", action = "http://app1msc.assino.net#TaskManager:GetStatuses")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatuses", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatuses")
    @ResponseWrapper(localName = "GetStatusesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusesResponse")
    public StatusList getStatuses();

    /**
     * 
     * @param nameSubstring
     * @return
     *     returns net.assino.app1msc.ProjectList
     */
    @WebMethod(operationName = "FindProjects", action = "http://app1msc.assino.net#TaskManager:FindProjects")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "FindProjects", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindProjects")
    @ResponseWrapper(localName = "FindProjectsResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindProjectsResponse")
    public ProjectList findProjects(
        @WebParam(name = "NameSubstring", targetNamespace = "http://app1msc.assino.net")
        String nameSubstring);

    /**
     * 
     * @param nameSubstring
     * @param project
     * @return
     *     returns net.assino.app1msc.ProjectStageList
     */
    @WebMethod(operationName = "FindProjectsStages", action = "http://app1msc.assino.net#TaskManager:FindProjectsStages")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "FindProjectsStages", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindProjectsStages")
    @ResponseWrapper(localName = "FindProjectsStagesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindProjectsStagesResponse")
    public ProjectStageList findProjectsStages(
        @WebParam(name = "Project", targetNamespace = "http://app1msc.assino.net")
        Project project,
        @WebParam(name = "NameSubstring", targetNamespace = "http://app1msc.assino.net")
        String nameSubstring);

    /**
     * 
     * @param nameSubstring
     * @param externalIDSubstring
     * @return
     *     returns net.assino.app1msc.TaskList
     */
    @WebMethod(operationName = "FindTasks", action = "http://app1msc.assino.net#TaskManager:FindTasks")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "FindTasks", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindTasks")
    @ResponseWrapper(localName = "FindTasksResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindTasksResponse")
    public TaskList findTasks(
        @WebParam(name = "NameSubstring", targetNamespace = "http://app1msc.assino.net")
        String nameSubstring,
        @WebParam(name = "ExternalIDSubstring", targetNamespace = "http://app1msc.assino.net")
        String externalIDSubstring);

    /**
     * 
     * @param nameSubstring
     * @return
     *     returns net.assino.app1msc.EmployeeList
     */
    @WebMethod(operationName = "FindEmployees", action = "http://app1msc.assino.net#TaskManager:FindEmployees")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "FindEmployees", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindEmployees")
    @ResponseWrapper(localName = "FindEmployeesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindEmployeesResponse")
    public EmployeeList findEmployees(
        @WebParam(name = "NameSubstring", targetNamespace = "http://app1msc.assino.net")
        String nameSubstring);

    /**
     * 
     * @param nameSubstring
     * @return
     *     returns net.assino.app1msc.StatusList
     */
    @WebMethod(operationName = "FindStatuses", action = "http://app1msc.assino.net#TaskManager:FindStatuses")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "FindStatuses", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindStatuses")
    @ResponseWrapper(localName = "FindStatusesResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.FindStatusesResponse")
    public StatusList findStatuses(
        @WebParam(name = "NameSubstring", targetNamespace = "http://app1msc.assino.net")
        String nameSubstring);

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Employee
     */
    @WebMethod(operationName = "GetCurrentUser", action = "http://app1msc.assino.net#TaskManager:GetCurrentUser")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetCurrentUser", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetCurrentUser")
    @ResponseWrapper(localName = "GetCurrentUserResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetCurrentUserResponse")
    public Employee getCurrentUser();

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Status
     */
    @WebMethod(operationName = "GetStatusInProgress", action = "http://app1msc.assino.net#TaskManager:GetStatusInProgress")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatusInProgress", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusInProgress")
    @ResponseWrapper(localName = "GetStatusInProgressResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusInProgressResponse")
    public Status getStatusInProgress();

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Status
     */
    @WebMethod(operationName = "GetStatusPaused", action = "http://app1msc.assino.net#TaskManager:GetStatusPaused")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatusPaused", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusPaused")
    @ResponseWrapper(localName = "GetStatusPausedResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusPausedResponse")
    public Status getStatusPaused();

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Status
     */
    @WebMethod(operationName = "GetStatusDone", action = "http://app1msc.assino.net#TaskManager:GetStatusDone")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatusDone", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusDone")
    @ResponseWrapper(localName = "GetStatusDoneResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusDoneResponse")
    public Status getStatusDone();

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Status
     */
    @WebMethod(operationName = "GetStatusDeployed", action = "http://app1msc.assino.net#TaskManager:GetStatusDeployed")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatusDeployed", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusDeployed")
    @ResponseWrapper(localName = "GetStatusDeployedResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusDeployedResponse")
    public Status getStatusDeployed();

    /**
     * 
     * @return
     *     returns net.assino.app1msc.Status
     */
    @WebMethod(operationName = "GetStatusInDevGroup", action = "http://app1msc.assino.net#TaskManager:GetStatusInDevGroup")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetStatusInDevGroup", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusInDevGroup")
    @ResponseWrapper(localName = "GetStatusInDevGroupResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetStatusInDevGroupResponse")
    public Status getStatusInDevGroup();

    /**
     * 
     * @param task
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetStatusInProgress", action = "http://app1msc.assino.net#TaskManager:SetStatusInProgress")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "SetStatusInProgress", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusInProgress")
    @ResponseWrapper(localName = "SetStatusInProgressResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusInProgressResponse")
    public boolean setStatusInProgress(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @param task
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetStatusPaused", action = "http://app1msc.assino.net#TaskManager:SetStatusPaused")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "SetStatusPaused", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusPaused")
    @ResponseWrapper(localName = "SetStatusPausedResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusPausedResponse")
    public boolean setStatusPaused(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @param task
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetStatusDone", action = "http://app1msc.assino.net#TaskManager:SetStatusDone")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "SetStatusDone", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusDone")
    @ResponseWrapper(localName = "SetStatusDoneResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusDoneResponse")
    public boolean setStatusDone(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @param task
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetStatusDeployed", action = "http://app1msc.assino.net#TaskManager:SetStatusDeployed")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "SetStatusDeployed", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusDeployed")
    @ResponseWrapper(localName = "SetStatusDeployedResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetStatusDeployedResponse")
    public boolean setStatusDeployed(
        @WebParam(name = "Task", targetNamespace = "http://app1msc.assino.net")
        Task task);

    /**
     * 
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "GetAutoFillDailyReports", action = "http://app1msc.assino.net#TaskManager:GetAutoFillDailyReports")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "GetAutoFillDailyReports", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetAutoFillDailyReports")
    @ResponseWrapper(localName = "GetAutoFillDailyReportsResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.GetAutoFillDailyReportsResponse")
    public boolean getAutoFillDailyReports();

    /**
     * 
     * @param value
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SetAutoFillDailyReports", action = "http://app1msc.assino.net#TaskManager:SetAutoFillDailyReports")
    @WebResult(targetNamespace = "http://app1msc.assino.net")
    @RequestWrapper(localName = "SetAutoFillDailyReports", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetAutoFillDailyReports")
    @ResponseWrapper(localName = "SetAutoFillDailyReportsResponse", targetNamespace = "http://app1msc.assino.net", className = "net.assino.app1msc.SetAutoFillDailyReportsResponse")
    public boolean setAutoFillDailyReports(
        @WebParam(name = "Value", targetNamespace = "http://app1msc.assino.net")
        boolean value);

}
